-- 000 (DEMO 1.7.1): БАЗОВА СХЕМА — повне відтворення системи «з нуля».
--
-- Виправляє відтворюваність: раніше в міграціях не було створення
-- monitoring_requests / monitoring_logs / monitoring_request_versions /
-- notification_log, а closeout_requests у міграції 002 відставав від
-- фактичної структури. Цей файл звірений із живою БД 1-в-1.
--
-- Безпечний до повторного запуску (IF NOT EXISTS). На вже розгорнутій базі
-- нічого не змінює. Порядок розгортання з нуля:
--   000 → 002 → 003 → 007 (001, 004–006 уже враховані в цьому файлі).

CREATE TABLE IF NOT EXISTS public.monitoring_requests (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year                text,
    quarter             text,
    department          text,
    responsible_person  text,
    phone               text,
    email               text,
    strat_code          text,
    object_name         text        DEFAULT '',
    indicator_name      text        DEFAULT '',
    status              text,
    progress_text       text,
    numeric_value       text,
    risks               text,
    submitted_at        timestamptz,
    approval_status     text        DEFAULT 'Очікує погодження',
    admin_comment       text,
    created_at          timestamptz DEFAULT now(),
    start_date          text,
    end_date            text,
    file_names          text,
    file_urls           text,
    npa_link            text,
    approval_chain      text,
    chain_stage         integer     DEFAULT 0,
    scheme_label        text,
    object_kind         text        DEFAULT 'measure',
    as_of_date          text
);

CREATE TABLE IF NOT EXISTS public.monitoring_logs (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id    bigint,
    action        text,
    old_status    text,
    new_status    text,
    admin_comment text,
    changed_by    text,
    changed_at    timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.monitoring_request_versions (
    id                 bigserial PRIMARY KEY,
    request_id         bigint  NOT NULL,
    version_number     integer NOT NULL,
    year               text,
    quarter            text,
    department         text,
    responsible_person text,
    phone              text,
    email              text,
    strat_code         text,
    status             text,
    progress_text      text,
    numeric_value      text,
    risks              text,
    file_names         text,
    file_urls          text,
    approval_status    text,
    admin_comment      text,
    start_date         text,
    end_date           text,
    created_at         timestamptz DEFAULT now(),
    created_by         text DEFAULT 'system',
    npa_link           text DEFAULT '',
    approval_chain     text DEFAULT '',
    chain_stage        integer DEFAULT 0,
    scheme_label       text DEFAULT '',
    object_kind        text DEFAULT '',
    object_name        text DEFAULT '',
    indicator_name     text DEFAULT '',
    as_of_date         text DEFAULT ''
);

CREATE TABLE IF NOT EXISTS public.notification_log (
    id                bigserial PRIMARY KEY,
    recipient_email   text NOT NULL,
    recipient_role    text,
    notification_type text NOT NULL,
    related_key       text NOT NULL DEFAULT '',
    subject           text,
    body_preview      text,
    sent_at           timestamptz NOT NULL DEFAULT now(),
    status            text NOT NULL DEFAULT 'sent',
    error             text
);

-- Індекси (дзеркало міграції 006)
CREATE INDEX IF NOT EXISTS idx_monitoring_requests_code_period
    ON public.monitoring_requests (strat_code, year, quarter);
CREATE INDEX IF NOT EXISTS idx_monitoring_requests_approval_status
    ON public.monitoring_requests (approval_status);

-- RLS: monitoring_request_versions — дозвільні політики (як у живій БД);
-- решта політик — у міграції 007.
ALTER TABLE public.monitoring_request_versions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read versions"   ON public.monitoring_request_versions;
DROP POLICY IF EXISTS "Allow public insert versions" ON public.monitoring_request_versions;
DROP POLICY IF EXISTS "Allow public update versions" ON public.monitoring_request_versions;
CREATE POLICY "Allow public read versions"   ON public.monitoring_request_versions FOR SELECT USING (true);
CREATE POLICY "Allow public insert versions" ON public.monitoring_request_versions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update versions" ON public.monitoring_request_versions FOR UPDATE USING (true) WITH CHECK (true);
ALTER TABLE public.notification_log  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.archive_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.closeout_requests ENABLE ROW LEVEL SECURITY;
