-- 012 (ДЕМО 2.0, Етап 2): атомарні переходи заявок і ручних закриттів.
--
-- Кожна публічна transition_* функція виконується PostgreSQL як одна
-- транзакція: перевіряє поточний стан, блокує рядок, оновлює об'єкт,
-- створює версію нового стану та пише журнал. Очікувані конфлікти
-- повертаються як JSON із success=false; неочікувана SQL-помилка відкочує все.

begin;

-- Відкликання стає м'яким: заявка зникає з робочих вибірок, але рядок,
-- версії та журнал не видаляються каскадно.
alter table public.monitoring_requests
    drop constraint if exists chk_approval_status;

alter table public.monitoring_requests
    add constraint chk_approval_status check (approval_status in (
        'Очікує погодження',
        'Очікує: Керівник ССП',
        'Очікує: Керівник управління',
        'Очікує: Заступник керівника ССП',
        'Очікує: Супер-адмін',
        'Повернуто на доопрацювання',
        'Погоджено',
        'Відкликано'
    ));

drop index if exists public.uq_measure_request_per_period;
create unique index uq_measure_request_per_period
    on public.monitoring_requests (strat_code, year, quarter)
    where object_kind = 'measure'
      and approval_status <> 'Відкликано';

-- Версії запитів на ручне закриття.
create table if not exists public.closeout_request_versions (
    id                  bigint generated by default as identity primary key,
    closeout_request_id bigint not null
        references public.closeout_requests(id) on delete cascade,
    version_number      integer not null,
    snapshot_data       jsonb not null,
    created_at          timestamptz not null default now(),
    created_by          text not null default 'system',
    unique (closeout_request_id, version_number)
);

create index if not exists idx_closeout_request_versions_request
    on public.closeout_request_versions (closeout_request_id, version_number);

alter table public.closeout_request_versions enable row level security;
drop policy if exists closeout_versions_all_select on public.closeout_request_versions;
drop policy if exists closeout_versions_all_insert on public.closeout_request_versions;
create policy closeout_versions_all_select
    on public.closeout_request_versions for select using (true);
create policy closeout_versions_all_insert
    on public.closeout_request_versions for insert with check (true);

grant select, insert on public.closeout_request_versions
    to anon, authenticated, service_role;
grant usage, select on sequence public.closeout_request_versions_id_seq
    to anon, authenticated, service_role;

create schema if not exists monitoring_internal;
grant usage on schema monitoring_internal to anon, authenticated, service_role;

create or replace function monitoring_internal.actor_label(p_actor jsonb)
returns text
language sql
immutable
security invoker
set search_path = pg_catalog
as $$
    select concat_ws(
        ' · ',
        nullif(btrim(coalesce(p_actor->>'role', '')), ''),
        nullif(btrim(coalesce(p_actor->>'name', '')), ''),
        case
            when nullif(btrim(coalesce(p_actor->>'email', '')), '') is not null
            then '<' || lower(btrim(p_actor->>'email')) || '>'
            else null
        end
    );
$$;

create or replace function monitoring_internal.snapshot_request(
    p_request_id bigint,
    p_created_by text
)
returns integer
language plpgsql
security invoker
set search_path = public, pg_catalog
as $$
declare
    v_version integer;
begin
    select coalesce(max(version_number), 0) + 1
      into v_version
      from public.monitoring_request_versions
     where request_id = p_request_id;

    insert into public.monitoring_request_versions (
        request_id, version_number, year, quarter, department,
        responsible_person, phone, email, strat_code, status,
        progress_text, numeric_value, value_text, risks, file_names,
        file_urls, approval_status, admin_comment, start_date, end_date,
        created_by, npa_link, approval_chain, chain_stage, scheme_label,
        object_kind, object_name, indicator_name, as_of_date
    )
    select
        r.id, v_version, r.year, r.quarter, r.department,
        r.responsible_person, r.phone, r.email, r.strat_code, r.status,
        r.progress_text, r.numeric_value, r.value_text, r.risks, r.file_names,
        r.file_urls, r.approval_status, r.admin_comment, r.start_date, r.end_date,
        coalesce(nullif(btrim(p_created_by), ''), 'system'),
        r.npa_link, r.approval_chain, r.chain_stage, r.scheme_label,
        r.object_kind, r.object_name, r.indicator_name, r.as_of_date
      from public.monitoring_requests r
     where r.id = p_request_id;

    if not found then
        raise exception 'Заявку % не знайдено під час створення версії.', p_request_id;
    end if;

    return v_version;
end;
$$;

create or replace function monitoring_internal.snapshot_closeout(
    p_closeout_id bigint,
    p_created_by text
)
returns integer
language plpgsql
security invoker
set search_path = public, pg_catalog
as $$
declare
    v_version integer;
begin
    select coalesce(max(version_number), 0) + 1
      into v_version
      from public.closeout_request_versions
     where closeout_request_id = p_closeout_id;

    insert into public.closeout_request_versions (
        closeout_request_id, version_number, snapshot_data, created_by
    )
    select
        c.id,
        v_version,
        to_jsonb(c),
        coalesce(nullif(btrim(p_created_by), ''), 'system')
      from public.closeout_requests c
     where c.id = p_closeout_id;

    if not found then
        raise exception 'Запит на ручне закриття % не знайдено під час створення версії.', p_closeout_id;
    end if;

    return v_version;
end;
$$;

create or replace function monitoring_internal.write_log(
    p_request_id bigint,
    p_action text,
    p_old_status text,
    p_new_status text,
    p_comment text,
    p_actor jsonb,
    p_strat_code text,
    p_related_table text,
    p_related_key text,
    p_details jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security invoker
set search_path = public, monitoring_internal, pg_catalog
as $$
declare
    v_log_id bigint;
    v_actor_email text := lower(btrim(coalesce(p_actor->>'email', '')));
    v_actor_name text := btrim(coalesce(p_actor->>'name', ''));
    v_actor_role text := btrim(coalesce(p_actor->>'role', ''));
begin
    insert into public.monitoring_logs (
        request_id, action, old_status, new_status, admin_comment,
        changed_by, changed_at, actor_email, actor_name, actor_role,
        strat_code, related_table, related_key, payload_json
    ) values (
        p_request_id,
        coalesce(p_action, ''),
        coalesce(p_old_status, ''),
        coalesce(p_new_status, ''),
        coalesce(p_comment, ''),
        monitoring_internal.actor_label(p_actor),
        now(),
        v_actor_email,
        v_actor_name,
        v_actor_role,
        coalesce(p_strat_code, ''),
        coalesce(nullif(p_related_table, ''), 'monitoring_requests'),
        coalesce(p_related_key, ''),
        coalesce(p_details, '{}'::jsonb)::text
    )
    returning id into v_log_id;

    return v_log_id;
end;
$$;

-- Погодження поточного кроку, передавання наступній ланці або остаточне
-- погодження з одночасним final_locked.
create or replace function public.transition_approve_request_step(
    p_request_id bigint,
    p_expected_status text,
    p_expected_chain_stage integer,
    p_new_status text,
    p_new_chain_stage integer,
    p_approval_chain text,
    p_comment text,
    p_action text,
    p_actor jsonb,
    p_created_by text
)
returns jsonb
language plpgsql
security invoker
set search_path = public, monitoring_internal, pg_catalog
as $$
declare
    v_row public.monitoring_requests%rowtype;
    v_version integer;
    v_allowed text[] := array[
        'Очікує погодження',
        'Очікує: Керівник ССП',
        'Очікує: Керівник управління',
        'Очікує: Заступник керівника ССП',
        'Очікує: Супер-адмін',
        'Погоджено'
    ];
begin
    select * into v_row
      from public.monitoring_requests
     where id = p_request_id
     for update;

    if not found then
        return jsonb_build_object('success', false, 'code', 'not_found',
                                  'message', 'Заявку не знайдено.');
    end if;
    if v_row.final_locked then
        return jsonb_build_object('success', false, 'code', 'already_final_locked',
                                  'message', 'Заявку вже остаточно погоджено.');
    end if;
    if v_row.approval_status is distinct from p_expected_status
       or coalesce(v_row.chain_stage, 0) is distinct from coalesce(p_expected_chain_stage, 0)
    then
        return jsonb_build_object(
            'success', false,
            'code', 'state_changed',
            'message', 'Перехід недопустимий: заявку вже опрацювала інша ланка.',
            'current_status', v_row.approval_status,
            'current_chain_stage', coalesce(v_row.chain_stage, 0)
        );
    end if;
    if not (p_new_status = any(v_allowed)) then
        return jsonb_build_object('success', false, 'code', 'invalid_target_status',
                                  'message', 'Задано недопустимий новий статус.');
    end if;
    if coalesce(p_new_chain_stage, 0) < coalesce(v_row.chain_stage, 0) then
        return jsonb_build_object('success', false, 'code', 'invalid_stage_direction',
                                  'message', 'Погодження не може повернути заявку на попередню ланку.');
    end if;

    update public.monitoring_requests
       set approval_status = p_new_status,
           chain_stage = coalesce(p_new_chain_stage, chain_stage),
           approval_chain = coalesce(p_approval_chain, approval_chain),
           admin_comment = coalesce(p_comment, ''),
           final_locked = case when p_new_status = 'Погоджено' then true else final_locked end,
           final_locked_at = case
               when p_new_status = 'Погоджено' then coalesce(final_locked_at, now())
               else final_locked_at
           end
     where id = p_request_id;

    v_version := monitoring_internal.snapshot_request(
        p_request_id,
        coalesce(p_created_by, 'Погодження')
    );

    perform monitoring_internal.write_log(
        p_request_id, p_action, v_row.approval_status, p_new_status,
        p_comment, p_actor, v_row.strat_code, 'monitoring_requests',
        p_request_id::text,
        jsonb_build_object('version_number', v_version)
    );

    return jsonb_build_object(
        'success', true, 'code', 'ok', 'message', 'Перехід виконано.',
        'request_id', p_request_id, 'new_status', p_new_status,
        'new_chain_stage', p_new_chain_stage,
        'final_locked', p_new_status = 'Погоджено',
        'version_number', v_version
    );
end;
$$;

-- Повернення подавачу або на попередню ланку.
create or replace function public.transition_return_request(
    p_request_id bigint,
    p_expected_status text,
    p_expected_chain_stage integer,
    p_new_status text,
    p_new_chain_stage integer,
    p_comment text,
    p_action text,
    p_actor jsonb,
    p_created_by text
)
returns jsonb
language plpgsql
security invoker
set search_path = public, monitoring_internal, pg_catalog
as $$
declare
    v_row public.monitoring_requests%rowtype;
    v_version integer;
    v_allowed text[] := array[
        'Повернуто на доопрацювання',
        'Очікує погодження',
        'Очікує: Керівник ССП',
        'Очікує: Керівник управління',
        'Очікує: Заступник керівника ССП',
        'Очікує: Супер-адмін'
    ];
begin
    if nullif(btrim(coalesce(p_comment, '')), '') is null then
        return jsonb_build_object('success', false, 'code', 'comment_required',
                                  'message', 'Для повернення обов’язковий коментар.');
    end if;

    select * into v_row
      from public.monitoring_requests
     where id = p_request_id
     for update;

    if not found then
        return jsonb_build_object('success', false, 'code', 'not_found',
                                  'message', 'Заявку не знайдено.');
    end if;
    if v_row.final_locked then
        return jsonb_build_object('success', false, 'code', 'already_final_locked',
                                  'message', 'Остаточно погоджену заявку повернути неможливо.');
    end if;
    if v_row.approval_status is distinct from p_expected_status
       or coalesce(v_row.chain_stage, 0) is distinct from coalesce(p_expected_chain_stage, 0)
    then
        return jsonb_build_object(
            'success', false, 'code', 'state_changed',
            'message', 'Перехід недопустимий: заявку вже опрацювала інша ланка.',
            'current_status', v_row.approval_status,
            'current_chain_stage', coalesce(v_row.chain_stage, 0)
        );
    end if;
    if not (p_new_status = any(v_allowed)) then
        return jsonb_build_object('success', false, 'code', 'invalid_target_status',
                                  'message', 'Задано недопустимий статус повернення.');
    end if;
    if coalesce(p_new_chain_stage, 0) > coalesce(v_row.chain_stage, 0) then
        return jsonb_build_object('success', false, 'code', 'invalid_stage_direction',
                                  'message', 'Повернення не може передати заявку на наступну ланку.');
    end if;

    update public.monitoring_requests
       set approval_status = p_new_status,
           chain_stage = coalesce(p_new_chain_stage, chain_stage),
           admin_comment = p_comment
     where id = p_request_id;

    v_version := monitoring_internal.snapshot_request(
        p_request_id,
        coalesce(p_created_by, 'Повернення')
    );

    perform monitoring_internal.write_log(
        p_request_id, p_action, v_row.approval_status, p_new_status,
        p_comment, p_actor, v_row.strat_code, 'monitoring_requests',
        p_request_id::text,
        jsonb_build_object('version_number', v_version)
    );

    return jsonb_build_object(
        'success', true, 'code', 'ok', 'message', 'Заявку повернуто.',
        'request_id', p_request_id, 'new_status', p_new_status,
        'new_chain_stage', p_new_chain_stage,
        'version_number', v_version
    );
end;
$$;

-- Відкликання без фізичного DELETE: історія залишається, робочі лоадери
-- приховують approval_status='Відкликано'.
create or replace function public.transition_withdraw_request(
    p_request_id bigint,
    p_expected_status text,
    p_expected_chain_stage integer,
    p_comment text,
    p_actor jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = public, monitoring_internal, pg_catalog
as $$
declare
    v_row public.monitoring_requests%rowtype;
    v_version integer;
begin
    select * into v_row
      from public.monitoring_requests
     where id = p_request_id
     for update;

    if not found then
        return jsonb_build_object('success', false, 'code', 'not_found',
                                  'message', 'Заявку не знайдено.');
    end if;
    if v_row.final_locked then
        return jsonb_build_object('success', false, 'code', 'already_final_locked',
                                  'message', 'Остаточно погоджену заявку відкликати неможливо.');
    end if;
    if v_row.approval_status is distinct from p_expected_status
       or coalesce(v_row.chain_stage, 0) is distinct from coalesce(p_expected_chain_stage, 0)
    then
        return jsonb_build_object(
            'success', false, 'code', 'state_changed',
            'message', 'Відкликання недопустиме: заявку вже опрацювала інша ланка.',
            'current_status', v_row.approval_status,
            'current_chain_stage', coalesce(v_row.chain_stage, 0)
        );
    end if;

    update public.monitoring_requests
       set approval_status = 'Відкликано',
           admin_comment = coalesce(p_comment, 'Відкликано подавачем')
     where id = p_request_id;

    v_version := monitoring_internal.snapshot_request(
        p_request_id, 'ССП / відкликано'
    );

    perform monitoring_internal.write_log(
        p_request_id, 'Відкликання заявки подавачем',
        v_row.approval_status, 'Відкликано', p_comment, p_actor,
        v_row.strat_code, 'monitoring_requests', p_request_id::text,
        jsonb_build_object('version_number', v_version)
    );

    return jsonb_build_object(
        'success', true, 'code', 'ok', 'message', 'Заявку відкликано.',
        'request_id', p_request_id,
        'version_number', v_version
    );
end;
$$;

-- Створення запиту на ручне закриття. Для супер-адміна початковий
-- статус може бути одразу «Підтверджено»; insert, версія і журнал атомарні.
create or replace function public.transition_create_closeout(
    p_payload jsonb,
    p_actor jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = public, monitoring_internal, pg_catalog
as $$
declare
    v_row public.closeout_requests%rowtype;
    v_version integer;
    v_status text := coalesce(nullif(btrim(p_payload->>'approval_status'), ''),
                              'Очікує підтвердження');
begin
    if nullif(btrim(coalesce(p_payload->>'strat_code', '')), '') is null then
        return jsonb_build_object('success', false, 'code', 'strat_code_required',
                                  'message', 'Не зазначено код заходу.');
    end if;
    if nullif(btrim(coalesce(p_payload->>'reason', '')), '') is null then
        return jsonb_build_object('success', false, 'code', 'reason_required',
                                  'message', 'Підстава ручного закриття обов’язкова.');
    end if;
    if v_status not in ('Очікує підтвердження', 'Підтверджено') then
        return jsonb_build_object('success', false, 'code', 'invalid_initial_status',
                                  'message', 'Недопустимий початковий статус ручного закриття.');
    end if;

    insert into public.closeout_requests (
        strat_code, period_year, period_quarter, admin_id, admin_email,
        reason, evidence_note, approval_status, superadmin_id, decided_at,
        npa_links, scope, head_status, head_email,
        assigned_superadmin_email, assigned_superadmin_name,
        senior_superadmin_email, senior_superadmin_name, routing_note
    ) values (
        btrim(p_payload->>'strat_code'),
        nullif(p_payload->>'period_year', '')::smallint,
        nullif(p_payload->>'period_quarter', '')::smallint,
        coalesce(p_payload->>'admin_id', ''),
        lower(btrim(coalesce(p_payload->>'admin_email', ''))),
        btrim(p_payload->>'reason'),
        coalesce(p_payload->>'evidence_note', ''),
        v_status,
        case when v_status = 'Підтверджено'
             then coalesce(nullif(p_payload->>'superadmin_id', ''),
                           p_actor->>'email', p_actor->>'name', '')
             else nullif(p_payload->>'superadmin_id', '') end,
        case when v_status = 'Підтверджено' then now() else null end,
        coalesce(p_payload->>'npa_links', ''),
        coalesce(nullif(p_payload->>'scope', ''), 'Квартал'),
        case when v_status = 'Підтверджено'
             then coalesce(nullif(p_payload->>'head_status', ''), 'Очікує реакції')
             else nullif(p_payload->>'head_status', '') end,
        nullif(p_payload->>'head_email', ''),
        nullif(p_payload->>'assigned_superadmin_email', ''),
        nullif(p_payload->>'assigned_superadmin_name', ''),
        nullif(p_payload->>'senior_superadmin_email', ''),
        nullif(p_payload->>'senior_superadmin_name', ''),
        nullif(p_payload->>'routing_note', '')
    ) returning * into v_row;

    v_version := monitoring_internal.snapshot_closeout(
        v_row.id, 'Ручне закриття / створення'
    );

    perform monitoring_internal.write_log(
        null,
        'Ручне закриття заходу',
        '',
        v_status,
        v_row.reason,
        p_actor,
        v_row.strat_code,
        'closeout_requests',
        v_row.id::text,
        jsonb_build_object(
            'version_number', v_version,
            'scope', v_row.scope,
            'year', v_row.period_year,
            'quarter', v_row.period_quarter
        )
    );

    return jsonb_build_object(
        'success', true, 'code', 'ok',
        'message', case when v_status = 'Підтверджено'
                        then 'Захід закрито вручну.'
                        else 'Запит на ручне закриття створено.' end,
        'closeout_id', v_row.id,
        'new_status', v_status,
        'version_number', v_version
    );
end;
$$;

-- Рішення супер-адміна щодо запиту на ручне закриття.
create or replace function public.transition_decide_closeout(
    p_closeout_id bigint,
    p_expected_status text,
    p_new_status text,
    p_decision_comment text,
    p_head_email text,
    p_actor jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = public, monitoring_internal, pg_catalog
as $$
declare
    v_row public.closeout_requests%rowtype;
    v_version integer;
    v_actor_id text := coalesce(p_actor->>'email', p_actor->>'name', '');
begin
    if p_new_status not in ('Підтверджено', 'Відхилено') then
        return jsonb_build_object('success', false, 'code', 'invalid_target_status',
                                  'message', 'Недопустиме рішення щодо ручного закриття.');
    end if;

    select * into v_row
      from public.closeout_requests
     where id = p_closeout_id
     for update;

    if not found then
        return jsonb_build_object('success', false, 'code', 'not_found',
                                  'message', 'Запит на ручне закриття не знайдено.');
    end if;
    if v_row.approval_status is distinct from p_expected_status then
        return jsonb_build_object(
            'success', false, 'code', 'state_changed',
            'message', 'Перехід недопустимий: цей запит уже розглянуто.',
            'current_status', v_row.approval_status
        );
    end if;

    update public.closeout_requests
       set approval_status = p_new_status,
           superadmin_id = v_actor_id,
           decided_at = now(),
           decision_comment = coalesce(p_decision_comment, ''),
           head_status = case
               when p_new_status = 'Підтверджено' then 'Очікує реакції'
               else head_status
           end,
           head_email = case
               when p_new_status = 'Підтверджено'
               then coalesce(nullif(btrim(p_head_email), ''), head_email)
               else head_email
           end
     where id = p_closeout_id;

    v_version := monitoring_internal.snapshot_closeout(
        p_closeout_id, 'Ручне закриття / після рішення'
    );

    perform monitoring_internal.write_log(
        null,
        'Закриття заходу: ' || p_new_status,
        v_row.approval_status,
        p_new_status,
        p_decision_comment,
        p_actor,
        v_row.strat_code,
        'closeout_requests',
        p_closeout_id::text,
        jsonb_build_object('version_number', v_version)
    );

    return jsonb_build_object(
        'success', true, 'code', 'ok', 'message', 'Рішення зафіксовано.',
        'closeout_id', p_closeout_id, 'new_status', p_new_status,
        'version_number', v_version
    );
end;
$$;

-- Окрема атомарна операція final_locked для службових сценаріїв.
create or replace function public.transition_set_final_locked(
    p_request_id bigint,
    p_expected_status text,
    p_comment text,
    p_action text,
    p_actor jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = public, monitoring_internal, pg_catalog
as $$
declare
    v_row public.monitoring_requests%rowtype;
    v_version integer;
begin
    select * into v_row
      from public.monitoring_requests
     where id = p_request_id
     for update;

    if not found then
        return jsonb_build_object('success', false, 'code', 'not_found',
                                  'message', 'Заявку не знайдено.');
    end if;
    if v_row.final_locked then
        return jsonb_build_object('success', false, 'code', 'already_final_locked',
                                  'message', 'Заявку вже остаточно закрито.');
    end if;
    if v_row.approval_status is distinct from p_expected_status
       or v_row.approval_status <> 'Погоджено'
    then
        return jsonb_build_object('success', false, 'code', 'invalid_state',
                                  'message', 'final_locked можна встановити лише погодженій заявці.');
    end if;

    update public.monitoring_requests
       set final_locked = true,
           final_locked_at = coalesce(final_locked_at, now()),
           admin_comment = coalesce(nullif(p_comment, ''), admin_comment)
     where id = p_request_id;

    v_version := monitoring_internal.snapshot_request(
        p_request_id, 'Система / final_locked'
    );

    perform monitoring_internal.write_log(
        p_request_id, coalesce(nullif(p_action, ''), 'Остаточне закриття заявки'),
        v_row.approval_status, v_row.approval_status, p_comment, p_actor,
        v_row.strat_code, 'monitoring_requests', p_request_id::text,
        jsonb_build_object('version_number', v_version)
    );

    return jsonb_build_object(
        'success', true, 'code', 'ok', 'message', 'Заявку остаточно закрито.',
        'request_id', p_request_id, 'final_locked', true,
        'version_number', v_version
    );
end;
$$;

-- Коригування даних уже остаточно закритої заявки супер-адміном.
create or replace function public.transition_correct_locked_request(
    p_request_id bigint,
    p_updates jsonb,
    p_reason text,
    p_actor jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = public, monitoring_internal, pg_catalog
as $$
declare
    v_row public.monitoring_requests%rowtype;
    v_before integer;
    v_after integer;
    v_bad_fields text[];
    v_allowed_fields text[] := array[
        'status', 'numeric_value', 'value_text', 'progress_text',
        'risks', 'npa_link'
    ];
begin
    if nullif(btrim(coalesce(p_reason, '')), '') is null then
        return jsonb_build_object('success', false, 'code', 'reason_required',
                                  'message', 'Для коригування обов’язкова підстава.');
    end if;

    select array_agg(keys.key order by keys.key)
      into v_bad_fields
      from jsonb_object_keys(coalesce(p_updates, '{}'::jsonb)) as keys(key)
     where not (keys.key = any(v_allowed_fields));

    if v_bad_fields is not null then
        return jsonb_build_object(
            'success', false, 'code', 'invalid_fields',
            'message', 'Спроба змінити заборонені поля закритої заявки.',
            'fields', to_jsonb(v_bad_fields)
        );
    end if;

    select * into v_row
      from public.monitoring_requests
     where id = p_request_id
     for update;

    if not found then
        return jsonb_build_object('success', false, 'code', 'not_found',
                                  'message', 'Заявку не знайдено.');
    end if;
    if not v_row.final_locked or v_row.approval_status <> 'Погоджено' then
        return jsonb_build_object('success', false, 'code', 'not_final_locked',
                                  'message', 'Коригування доступне лише для остаточно погодженої заявки.');
    end if;

    v_before := monitoring_internal.snapshot_request(
        p_request_id, 'Супер-адмін / до коригування'
    );

    update public.monitoring_requests
       set status = case
               when p_updates ? 'status' then nullif(p_updates->>'status', '')
               else status
           end,
           numeric_value = case
               when p_updates ? 'numeric_value'
               then nullif(p_updates->>'numeric_value', '')::numeric
               else numeric_value
           end,
           value_text = case
               when p_updates ? 'value_text' then nullif(p_updates->>'value_text', '')
               else value_text
           end,
           progress_text = case
               when p_updates ? 'progress_text' then coalesce(p_updates->>'progress_text', '')
               else progress_text
           end,
           risks = case
               when p_updates ? 'risks' then coalesce(p_updates->>'risks', '')
               else risks
           end,
           npa_link = case
               when p_updates ? 'npa_link' then coalesce(p_updates->>'npa_link', '')
               else npa_link
           end,
           admin_comment = 'Коригування супер-адміном після закриття: ' || btrim(p_reason)
     where id = p_request_id;

    v_after := monitoring_internal.snapshot_request(
        p_request_id, 'Супер-адмін / коригування після закриття'
    );

    perform monitoring_internal.write_log(
        p_request_id,
        'Коригування даних супер-адміном після закриття: версія '
            || v_before || ' → ' || v_after,
        v_row.approval_status,
        v_row.approval_status,
        'Підстава: ' || btrim(p_reason),
        p_actor,
        v_row.strat_code,
        'monitoring_requests',
        p_request_id::text,
        jsonb_build_object('version_before', v_before, 'version_after', v_after)
    );

    return jsonb_build_object(
        'success', true, 'code', 'ok', 'message', 'Дані скориговано.',
        'request_id', p_request_id,
        'version_before', v_before, 'version_after', v_after
    );
end;
$$;

-- Допоміжні функції не є прямими RPC-ендпойнтами.
revoke all on function monitoring_internal.actor_label(jsonb) from public;
revoke all on function monitoring_internal.snapshot_request(bigint, text) from public;
revoke all on function monitoring_internal.snapshot_closeout(bigint, text) from public;
revoke all on function monitoring_internal.write_log(bigint, text, text, text, text, jsonb, text, text, text, jsonb) from public;

grant execute on function monitoring_internal.actor_label(jsonb) to anon, authenticated, service_role;
grant execute on function monitoring_internal.snapshot_request(bigint, text) to anon, authenticated, service_role;
grant execute on function monitoring_internal.snapshot_closeout(bigint, text) to anon, authenticated, service_role;
grant execute on function monitoring_internal.write_log(bigint, text, text, text, text, jsonb, text, text, text, jsonb) to anon, authenticated, service_role;

revoke all on function public.transition_approve_request_step(bigint, text, integer, text, integer, text, text, text, jsonb, text) from public;
revoke all on function public.transition_return_request(bigint, text, integer, text, integer, text, text, jsonb, text) from public;
revoke all on function public.transition_withdraw_request(bigint, text, integer, text, jsonb) from public;
revoke all on function public.transition_create_closeout(jsonb, jsonb) from public;
revoke all on function public.transition_decide_closeout(bigint, text, text, text, text, jsonb) from public;
revoke all on function public.transition_set_final_locked(bigint, text, text, text, jsonb) from public;
revoke all on function public.transition_correct_locked_request(bigint, jsonb, text, jsonb) from public;

grant execute on function public.transition_approve_request_step(bigint, text, integer, text, integer, text, text, text, jsonb, text) to anon, authenticated, service_role;
grant execute on function public.transition_return_request(bigint, text, integer, text, integer, text, text, jsonb, text) to anon, authenticated, service_role;
grant execute on function public.transition_withdraw_request(bigint, text, integer, text, jsonb) to anon, authenticated, service_role;
grant execute on function public.transition_create_closeout(jsonb, jsonb) to anon, authenticated, service_role;
grant execute on function public.transition_decide_closeout(bigint, text, text, text, text, jsonb) to anon, authenticated, service_role;
grant execute on function public.transition_set_final_locked(bigint, text, text, text, jsonb) to anon, authenticated, service_role;
grant execute on function public.transition_correct_locked_request(bigint, jsonb, text, jsonb) to anon, authenticated, service_role;

commit;
