-- Централізовані періоди, за якими моніторинг не проводиться.
-- Заблокований період завжди відображається як «Не настав час» і
-- виключається з розрахунків виконання.

CREATE TABLE IF NOT EXISTS public.period_locks (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year       integer NOT NULL,
    quarter    integer NOT NULL CHECK (quarter BETWEEN 1 AND 4),
    locked     boolean NOT NULL DEFAULT true,
    reason     text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT period_locks_year_quarter_key UNIQUE (year, quarter)
);

INSERT INTO public.period_locks (year, quarter, locked, reason)
VALUES
    (2026, 1, true, 'Моніторинг за період не проводиться'),
    (2026, 2, true, 'Моніторинг за період не проводиться')
ON CONFLICT (year, quarter)
DO UPDATE SET locked = EXCLUDED.locked, reason = EXCLUDED.reason;

-- Таблиця читається застосунком через Supabase Data API.
ALTER TABLE public.period_locks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read period locks" ON public.period_locks;
CREATE POLICY "Allow read period locks"
ON public.period_locks
FOR SELECT
TO anon, authenticated
USING (true);

GRANT SELECT ON TABLE public.period_locks TO anon, authenticated;
